/**
 * Chaînes de permissions alignées sur le backend (source de vérité :
 * apps/api/src/common/tenant/permissions.ts). Le frontend ne recopie PAS la
 * matrice rôle → permissions : les permissions effectives viennent de
 * GET /organizations/:id. Ces constantes ne servent qu'à référencer les noms.
 */
export const PERMISSIONS = {
  ORGANIZATION_READ: 'organization.read',
  ORGANIZATION_UPDATE: 'organization.update',
  ORGANIZATION_ARCHIVE: 'organization.archive',
  SETTINGS_MANAGE: 'settings.manage',
  MEMBERS_READ: 'members.read',
  MEMBERS_INVITE: 'members.invite',
  MEMBERS_UPDATE_ROLE: 'members.updateRole',
  MEMBERS_REMOVE: 'members.remove',
  INVITATIONS_READ: 'invitations.read',
  INVITATIONS_CANCEL: 'invitations.cancel',
  SHOPS_READ: 'shops.read',
  SHOPS_CREATE: 'shops.create',
  SHOPS_UPDATE: 'shops.update',
  SHOPS_ACTIVATE: 'shops.activate',
  SHOPS_ARCHIVE: 'shops.archive',
  SHOPS_MANAGE_SETTINGS: 'shops.manageSettings',
  WHATSAPP_CHANNELS_READ: 'whatsappChannels.read',
  WHATSAPP_CHANNELS_MANAGE: 'whatsappChannels.manage',
  CONTACTS_READ: 'contacts.read',
  CONTACTS_UPDATE: 'contacts.update',
  CONVERSATIONS_READ: 'conversations.read',
  CONVERSATIONS_REPLY: 'conversations.reply',
  CONVERSATIONS_ASSIGN: 'conversations.assign',
  CONVERSATIONS_UPDATE_STATUS: 'conversations.updateStatus',
  CONVERSATIONS_ADD_NOTE: 'conversations.addNote',
  CONVERSATIONS_MANAGE_TAGS: 'conversations.manageTags',
  CATEGORIES_READ: 'categories.read',
  CATEGORIES_CREATE: 'categories.create',
  CATEGORIES_UPDATE: 'categories.update',
  CATEGORIES_ARCHIVE: 'categories.archive',
  PRODUCTS_READ: 'products.read',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_UPDATE: 'products.update',
  PRODUCTS_ACTIVATE: 'products.activate',
  PRODUCTS_ARCHIVE: 'products.archive',
  INVENTORY_READ: 'inventory.read',
  INVENTORY_ADJUST: 'inventory.adjust',
  INVENTORY_VIEW_MOVEMENTS: 'inventory.viewMovements',
  CARTS_READ: 'carts.read',
  CARTS_CREATE: 'carts.create',
  CARTS_UPDATE: 'carts.update',
  CARTS_ABANDON: 'carts.abandon',
  CHECKOUT_READ: 'checkout.read',
  CHECKOUT_UPDATE: 'checkout.update',
  CHECKOUT_CONFIRM: 'checkout.confirm',
  STOCK_RESERVATIONS_READ: 'stockReservations.read',
  ORDERS_READ: 'orders.read',
  ORDERS_CREATE: 'orders.create',
  ORDERS_UPDATE_STATUS: 'orders.updateStatus',
  ORDERS_CANCEL: 'orders.cancel',
  ORDERS_ADD_NOTE: 'orders.addNote',
  ORDERS_VIEW_HISTORY: 'orders.viewHistory',
  AI_READ: 'ai.read',
  AI_CONFIGURE: 'ai.configure',
  AI_SUGGEST: 'ai.suggest',
  AI_ACCEPT_SUGGESTION: 'ai.acceptSuggestion',
  AI_REJECT_SUGGESTION: 'ai.rejectSuggestion',
  AI_VIEW_RUNS: 'ai.viewRuns',
  AI_ENABLE_AUTO_REPLY: 'ai.enableAutoReply',
  WALLET_READ: 'wallet.read',
  WALLET_VIEW_LEDGER: 'wallet.viewLedger',
  WALLET_TOP_UP: 'wallet.topUp',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
